site_name: "Materials: synthesis and stuff"
nav:
  - Home: 'index.md'
  - 'Labs':
    - 'Cobalt Preparation': 'labs/co-preparation.md'
    #- 'Glycerol-nitrate Synthesis': 'labs/glycerol-nitrate.md'
    - 'Powder Pressing': 'labs/pressing.md'
    - 'Particle Size Analysis': 'labs/particle-size.md'
    - 'SEM Sample Preparation': 'labs/sem-sample-preparation.md'
    - 'Dilatometry': 'labs/dilatometry.md'
    - 'Thermogravimetry': 'labs/thermogravimetry.md'
  - Origami Packets: 'origami.md'
  - About: 'about.md'
theme:
  name: material
  icon:
    logo: material/flask-outline
  favicon: assets/favicon/favicon.ico
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    #- navigation.tracking
    - navigation.expand
    #- navigation.instant
    #- navigation.instant.progress
plugins:
  - search
  - glightbox:
      touchNavigation: true
      loop: true
      effect: zoom
      width: 90%
      height: auto
      zoomable: true
markdown_extensions:
  - toc:
      permalink: true
  - footnotes
  - md_in_html
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - css/extra.css